language: java
jdk:
  - oraclejdk8
env: 
  - COVERAGE=0.3
  
install: "./gradlew clean jar"

script:
  - "./gradlew test"
  - "./gradlew jacocoTestReport"
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
  - "./gradlew test jacocoTestCoverageVerification"

deploy:
  provider: script
  script:
    - ECHO 'WIP'
  on:
    all_branches: true
