language: java
jdk:
  - oraclejdk8
env: 
  - COVERAGE=0.3
  
install: "./gradlew clean jar"

stages:
  - test
  - deploy

jobs:
  - include:
    - stage: test
      name: "1 check"
      install: skip
      script:
        - ./gradlew -p ./monolithic/ui check
      env: COVERAGE=0.5
    - script:
        - ./gradlew -p ./monolithic/service/cart check
      name: "2 check"
      install: skip
      env: COVERAGE=0.5
    - script:
        - ./gradlew -p ./monolithic/service/user check
      name: "3 check"
      install: skip
      env: COVERAGE=0.5
    - script:
        - ./gradlew -p ./monolithic/repository/order check
      name: "4 check"
      install: skip
      env: COVERAGE=0.3
    - script:
        - ./gradlew -p ./monolithic/repository/cart check
      name: "5 check"
      install: skip
      env: COVERAGE=0.5
    - script:
        - ./gradlew -p ./monolithic/repository/product check
      name: "6 check"
      install: skip
      env: COVERAGE=0.5
    - script:
        - ./gradlew -p ./monolithic/repository/user check
      name: "7 check"
      install: skip
      env: COVERAGE=0.3
    - stage: deploy
      install: skip
      deploy:
        provider: script
        script: "echo 'WIP'"
        on:
          all_branches: true